permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

name: "Hugo build and deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - develop # Set a branch to deploy

env:
  BRANCH_TO_DEPLOY: "develop"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out Hyas project
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Build production website
        run: yarn run build
        
      - name: Brotli compress the html, css and js files
        id: brotli
        uses: charlesworth/compress-action@1.0
        with:
          target-directory: 'public'

      - name: Archive build output
        run: tar --dereference --hard-dereference --directory public/ -cvf artifact.tar .
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: warn

  deploy:
    needs: build
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
        name: Deploy to GitHub Pages
