name: Node-js-CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16.x]

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: corepack enable yarn
        run: corepack enable yarn

      - name: Install dependencies
        run: yarn

      - name: Run test script
        run: yarn test

      - name: Build production website
        run: yarn run build
